baseURL = 'https://frogsniffa.github.io'
languageCode = 'en-us'
title = 'frogsniffa'
theme = 'brutalist-minimalist'
relativeURLs = true

[markup]
	[markup.highlight]
		noClasses = false
	[markup.tableOfContents]
		endLevel = 4
		ordered = true
		startLevel = 3

[params]
	siteBasename = 'frogsniffa'
	highlightStyle = 'emacs'
	enableKatex = true
